const mocks = {
  card: 'vcCard',
  recommended: 'vcRecommended',
  badge: 'vcBadge',
  header: 'vcCardHeader',
  icon: 'vcCardIcon',
  name: 'vcCardName',
  nameText: 'vcCardNameText',
  nameEn: 'vcCardNameEn',
  price: 'vcCardPrice',
  priceValue: 'vcCardPriceValue',
  estimateTag: 'vcCardEstimateTag',
  time: 'vcCardTime',
  wait: 'vcCardWait',
  waitLabel: 'vcCardWaitLabel',
  waitValue: 'vcCardWaitValue',
  arrival: 'vcCardArrival',
  arrivalLabel: 'vcCardArrivalLabel',
  arrivalValue: 'vcCardArrivalValue',
  ratings: 'vcCardRatings',
  rating: 'vcCardRating',
  ratingLabel: 'vcCardRatingLabel',
  ratingBadge: 'vcCardRatingBadge',
  eco: 'vcCardEco',
  notes: 'vcCardNotes',
  score1: 'score1',
  score2: 'score2',
  score3: 'score3',
  score4: 'score4',
  score5: 'score5',
};
export default mocks;
