export const landingCopy = {
  pill: 'Dịch vụ xe đưa đón sân bay',
  headline: 'Cách nhanh nhất từ sân bay về trung tâm.',
  subtitle:
    'So sánh xe buýt, Grab, taxi trong 5 giây. Không cần tải app, không cần đăng ký.',
  benefitFast: 'Nhanh nhất',
  benefitFastDesc: 'Lịch trình 26 chuyến/ngày',
  benefitSafe: 'An toàn',
  benefitSafeDesc: 'Tài xế xác minh, giá công khai',
  benefitCheap: 'Tiết kiệm',
  benefitCheapDesc: 'Chỉ 50.000đ cho xe buýt',
  fieldDeparture: 'Sân bay khởi hành',
  fieldDestination: 'Bạn muốn đi đâu?',
  fieldPeople: 'Số người',
  fieldLuggage: 'Hành lý',
  cta: 'Tìm phương tiện',
  socialProof: '4.9 điểm từ 12.000+ hành khách',
  footer: 'Lịch trình được tính cho khung giờ 12:00 — nhập giờ thực tế khi cần chính xác.',
  assumption: 'Đang giả định nhà ga T1 + hành lý xách tay — chi tiết hơn sau.',
  navBrand: 'Frylane',
  navBrandAccent: '',
  languagePill: 'EN',
  privacy: 'Privacy',
  terms: 'Terms',
  contact: 'Contact',
} as const;
